name: Ubuntu
on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    branches:
      - master

env:
  SCHEME: scheme
  IDRIS2_TESTS_CG: chez
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install build dependencies
        run: |
          sudo apt-get install -y chezscheme
          echo "::add-path::$HOME/.idris2/bin"
      - name: Build from bootstrap
        run: make bootstrap && make install
        shell: bash
      - name: Build and test self-hosted
        run: make clean && make all && make test INTERACTIVE=''
        shell: bash
