name: Windows
on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    branches:
      - master
env:
  MSYSTEM: MINGW64
  MSYS2_PATH_TYPE: inherit
  SCHEME: scheme
  CC: gcc

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Init
        run: |
          git config --global core.autocrlf false
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Chez Scheme
        run: |
          git clone --depth 1 https://github.com/cisco/ChezScheme
          c:\msys64\usr\bin\bash -l -c "pacman -S --noconfirm tar make"
          echo "PWD=$(c:\msys64\usr\bin\cygpath -u $(pwd))" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      - name: Configure and Build Chez Scheme
        run: |
          c:\msys64\usr\bin\bash -l -c "cd $env:PWD && cd ChezScheme && ./configure --threads && make"
      - name: Set Path
        run: |
          $chez="$(pwd)\ChezScheme\ta6nt\bin\ta6nt"
          $idris="$(pwd)\.idris2"
          echo "$chez" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "$idris\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "IDRIS_PREFIX=$idris" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "PREFIX=$(c:\msys64\usr\bin\cygpath -u $idris)" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      - name: Test Scheme
        run: |
          scheme --version
      - name: Bootstrap and install
        run: c:\msys64\usr\bin\bash -l -c "cd $env:PWD && make bootstrap && make bootstrap-test && make install"
