-module('Idris.Idris2.Compiler.Generated').
-compile('no_auto_import').
-compile('inline').
-compile({'inline_size',24}).
-export([
  'un--generatedString'/1
]).
'un--generatedString'(V0) -> ('Idris.Idris2.Prelude.Types.String':'un--++'(<<"@"/utf8>>, ('Idris.Idris2.Prelude.Types.String':'un--++'(<<"generated by Idris "/utf8>>, ('Idris.Idris2.Prelude.Types.String':'un--++'(('Idris.Idris2.Libraries.Data.Version':'dn--un--show_Show_Version'(('Idris.Idris2.Idris.Version':'un--version'()))), ('Idris.Idris2.Prelude.Types.String':'un--++'(<<", "/utf8>>, ('Idris.Idris2.Prelude.Types.String':'un--++'(V0, <<" backend"/utf8>>)))))))))).
