-module('Idris.Idris2.Idris.Version').
-compile('no_auto_import').
-compile('inline').
-compile({'inline_size',24}).
-export([
  'with--version-716'/1,
  'nested--2285-744--in--un--showTag'/5,
  'un--version'/0,
  'un--showVersion'/2
]).
'with--version-716'(V0) -> case V0 of {'Idris.Builtin.MkPair', E0, E1} -> (fun (V1, V2) -> case V2 of <<""/utf8>> -> {'Idris.Idris.Version.MkVersion', V1, {'Idris.Prelude.Types.Nothing'}}; _ -> {'Idris.Idris.Version.MkVersion', V1, {'Idris.Prelude.Types.Just', V2}} end end(E0, E1)); _ -> ('erlang':'throw'("Error: Unreachable branch")) end.
'nested--2285-744--in--un--showTag'(V0, V1, V2, V3, V4) -> case V3 of {'Idris.Prelude.Types.Nothing'} -> (fun () -> <<""/utf8>> end()); {'Idris.Prelude.Types.Just', E0} -> (fun (V5) -> ('Idris.Idris2.Prelude.Types.String':'un--++'(<<"-"/utf8>>, V5)) end(E0)); _ -> ('erlang':'throw'("Error: Unreachable branch")) end.
'un--version'() -> ('with--version-716'(('Idris.Idris2.IdrisPaths':'un--idrisVersion'()))).
'un--showVersion'(V0, V1) -> case V1 of {'Idris.Idris.Version.MkVersion', E0, E1} -> (fun (V2, V3) -> case V2 of {'Idris.Builtin.MkPair', E2, E3} -> (fun (V4, V5) -> case V5 of {'Idris.Builtin.MkPair', E4, E5} -> (fun (V6, V7) -> ('Idris.Idris2.Prelude.Types.String':'un--++'(('Idris.Idris2.Prelude.Interfaces':'un--concat'({'Idris.Builtin.MkPair', {'Idris.Prelude.Interfaces.MkFoldable', fun (V8) -> fun (V9) -> fun (V10) -> fun (V11) -> fun (V12) -> ('Idris.Idris2.Prelude.Types':'dn--un--foldr_Foldable_List'(V10, V11, V12)) end end end end end, fun (V13) -> fun (V14) -> fun (V15) -> fun (V16) -> fun (V17) -> ('Idris.Idris2.Prelude.Types':'dn--un--foldl_Foldable_List'(V15, V16, V17)) end end end end end, fun (V18) -> fun (V19) -> ('Idris.Idris2.Prelude.Types':'dn--un--null_Foldable_List'(V19)) end end, fun (V20) -> fun (V21) -> fun (V22) -> fun (V23) -> fun (V24) -> fun (V25) -> fun (V26) -> ('Idris.Idris2.Prelude.Types':'dn--un--foldlM_Foldable_List'(V23, V24, V25, V26)) end end end end end end end, fun (V27) -> fun (V28) -> ('Idris.Idris2.Prelude.Types':'dn--un--toList_Foldable_List'(V28)) end end, fun (V29) -> fun (V30) -> fun (V31) -> fun (V32) -> fun (V33) -> ('Idris.Idris2.Prelude.Types':'dn--un--foldMap_Foldable_List'(V31, V32, V33)) end end end end end}, {'Idris.Prelude.Interfaces.MkMonoid', fun (V34) -> fun (V35) -> ('Idris.Idris2.Prelude.Types':'dn--un--<+>_Semigroup_String'(V34, V35)) end end, ('Idris.Idris2.Prelude.Types':'dn--un--neutral_Monoid_String'())}}, ('Idris.Idris2.Data.List':'un--intersperse'(<<"."/utf8>>, ('Idris.Idris2.Prelude.Types':'dn--un--map_Functor_List'(fun (V36) -> ('Idris.Idris2.Prelude.Show':'dn--un--show_Show_Nat'(V36)) end, [V4 | [V6 | [V7 | []]]])))))), case V0 of 1 -> ('nested--2285-744--in--un--showTag'(V4, V6, V7, V3, V0)); 0 -> <<""/utf8>>; _ -> ('erlang':'throw'("Error: Unreachable branch")) end)) end(E4, E5)); _ -> ('erlang':'throw'("Error: Unreachable branch")) end end(E2, E3)); _ -> ('erlang':'throw'("Error: Unreachable branch")) end end(E0, E1)); _ -> ('erlang':'throw'("Error: Unreachable branch")) end.
