-module('Idris.Idris2.Compiler.Generated').
-compile('no_auto_import').
-compile('inline').
-compile({'inline_size',24}).
-export([
  'un--generatedString'/1
]).
'un--generatedString'(V0) -> <<<<"@"/utf8>>/binary, <<<<"generated by Idris "/utf8>>/binary, <<('Idris.Idris2.Libraries.Data.Version':'dn--un--show_Show_Version'(('Idris.Idris2.Idris.Version':'un--version'())))/binary, <<<<", "/utf8>>/binary, <<V0/binary, <<" backend"/utf8>>/binary>>/binary>>/binary>>/binary>>/binary>>.
