name: Nix
on:
  push:
    branches:
      - '*'
      - '!*-alpha*'
      - '!selfhosted-*'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Nix
      uses: cachix/install-nix-action@v12
    - name: Build using Nix
      run: nix-build
