name: Ubuntu
on:
  push:
    branches:
      - '*'
      - '!*-alpha*'
      - '!selfhosted-*'
  pull_request:
    branches:
      - master

env:
  SCHEME: scheme
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install build dependencies
        run: |
          sudo apt-get install -y chezscheme
          DEBIAN_FRONTEND=noninteractive sudo apt-get install -y erlang
      - name: Build and test Idris 2 from bootstrap
        run: cd idris2 && make bootstrap
        shell: bash
      - name: Run tests
        run: cd idris2 && make bootstrap-test
        shell: bash
