name: Ubuntu
on:
  push:
    branches:
      - '*'
      - '!*-alpha*'
      - '!selfhosted-*'
  pull_request:
    branches:
      - master

env:
  SCHEME: scheme

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install build dependencies
        run: |
          # Install Erlang before adding a new repository. Otherwise the install will fail with unmet dependencies.
          DEBIAN_FRONTEND=noninteractive sudo apt-get install --assume-yes erlang

          # Add a new repository to install newer version of Chez Scheme.
          echo "deb http://security.ubuntu.com/ubuntu hirsute universe" | sudo tee -a /etc/apt/sources.list
          sudo apt-get update
          sudo apt-get install --target-release hirsute --assume-yes chezscheme

          echo "$HOME/.idris2erl/bin" >> $GITHUB_PATH
      - name: Build Idris 2 from bootstrap
        run: cd idris2 && make bootstrap && make install
        shell: bash
      - name: Build Idris 2
        run: cd idris2 && IDRIS2_BOOT=idris2erl make clean && IDRIS2_BOOT=idris2erl make all && IDRIS2_BOOT=idris2erl make install
        shell: bash
      - name: Run tests
        run: cd idris2 && IDRIS2_BOOT=idris2erl make test INTERACTIVE=''
        shell: bash
