name: Ubuntu
on:
  push:
    branches:
      - '*'
      - '!*-alpha*'
      - '!selfhosted-*'
  pull_request:
    branches:
      - main

env:
  SCHEME: scheme

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install build dependencies
        run: |
          sudo apt-get install --assume-yes erlang chezscheme

          echo "$HOME/.idris2erl/bin" >> $GITHUB_PATH
      - name: Build Idris 2 from bootstrap
        run: cd idris2 && make bootstrap && make install
        shell: bash
      - name: Build Idris 2
        run: cd idris2 && IDRIS2_BOOT=idris2erl make clean && IDRIS2_BOOT=idris2erl make all && IDRIS2_BOOT=idris2erl make install
        shell: bash
      - name: Run tests
        run: cd idris2 && IDRIS2_BOOT=idris2erl make test INTERACTIVE=''
        shell: bash
      - name: Run samples
        run: cd samples && ./runsamples.sh
        shell: bash
